In [ ]:
%pip install pandasql

In [15]:
from main import main
from pandasql import sqldf

In [2]:
data = main('XPML11.SAO')

In [30]:
sqldf("""
SELECT close
FROM data
WHERE timestamp = (SELECT MAX(timestamp) FROM data)""", locals())['close']

0    113.98
Name: close, dtype: float64

In [31]:
data

,timestamp,open,high,low,close,adjusted close,volume,dividend amount
0,2024-07-05,112.75,113.98,109.40,113.98,113.9800,814049,0.00
1,2024-06-28,112.15,113.00,111.04,112.75,112.7500,595099,0.00
2,2024-06-21,110.85,114.00,109.28,114.00,114.0000,1070330,0.92
3,2024-06-14,113.15,113.50,109.01,110.86,109.9336,776550,0.00
4,2024-06-07,113.93,114.73,112.86,113.15,113.1500,747865,0.00
...,...,...,...,...,...,...,...,...
334,2018-02-02,105.89,106.29,102.01,104.00,72.6019,41776,0.00
335,2018-01-26,105.53,106.00,103.60,105.89,73.9213,39727,0.00
336,2018-01-19,105.40,106.30,104.62,106.30,74.2075,51315,0.00
337,2018-01-12,102.46,107.50,102.00,105.40,73.5792,56039,0.00
338,2018-01-05,101.49,102.49,100.49,102.46,71.5268,40621,0.00